In [71]:
import camelot
import pandas as pd
from pathlib import Path 

file = Path("C:\\Projects\\Python\\wealthsimple-portfolio-analytics-v2\\Data\\Data_Files\\2026-01.pdf")

# Extract tables from the PDF
tables = camelot.read_pdf(file,pages="all",flavor="stream")

Cannot set gray non-stroke color because /'p0' is an invalid float value

Cannot set gray non-stroke color because /'p1' is an invalid float value
Cannot set gray non-stroke color because /'p2' is an invalid float value
Cannot set gray non-stroke color because /'p3' is an invalid float value
Cannot set gray non-stroke color because /'p4' is an invalid float value
Cannot set gray non-stroke color because /'p5' is an invalid float value
Cannot set gray non-stroke color because /'p6' is an invalid float value
Cannot set gray non-stroke color because /'p7' is an invalid float value
Cannot set gray non-stroke color because /'p8' is an invalid float value
c:\Projects\Python\wealthsimple-portfolio-analytics-v2\.wsvenv\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (41.35433074999997, 140.4480562500001, 554.8393307499996, 834.44805625)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Projects\Python\wealthsimple-portfolio-analytics-v2\.wsvenv\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (83.8740155, 62.44805625000011, 511.2777655, 189.4480562500001)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
Cannot set gray non-stroke color because /'p9' is an invalid float value
Cannot set gray non-stroke color because /'p10' is an invalid float value
c:\Projects\Python\wealthsimple-portfolio-analytics-v2\.wsvenv\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (41.35433075, 655.75593, 553.8995807499998, 860.75593)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
Cannot set gray non-stroke color because /'p11' is an invalid float value
Cannot set gray non-stroke color because /'p12' is an invalid float value

In [72]:
tables[3]

In [73]:
print(tables[3].parsing_report)

{'accuracy': 96.82, 'whitespace': 46.83, 'order': 1, 'page': 3}

In [74]:
data = tables[3].df
data.head(50)
# data.to_csv("test.csv")

,0,1,2,3,4,5
0,,Activity - Current period,,,,
1,Date,Transaction Description,,,Debit ($) Credit ($) Balance ($),
2,2026-01-02,BUY,BN - Brookfield Corp.: Bought 0.0039 shares at...,$0.25,$0.00,$0.13
3,,,2025-12-31),,,
4,2026-01-02 DIV,,WN - George Weston Ltd.: Cash dividend distrib...,$0.00,$0.49,$0.62
5,,,record date of 2025-12-15,,,
6,2026-01-02,LOAN,ZGLD - BMO Gold Bullion ETF - CAD: 4.0000 Shar...,$0.00,$0.00,$0.62
7,,,2026-01-02),,,
8,2026-01-05,BUY,WN - George Weston Ltd.: Bought 0.0051 shares ...,$0.49,$0.00,$0.13
9,,,(executed at 2026-01-02),,,
10,2026-01-05 DIV,,CDZ - iShares S&P/TSX Canadian Dividend ETF: C...,$0.00,$0.12,$0.25
11,,,"received on 2026-01-05, record date of 2025-12-30",,,
12,2026-01-05 DIV,,ZEB - BMO Equal Weight Banks Index ETF: Cash d...,$0.00,$0.30,$0.55
13,,,"received on 2026-01-05, record date of 2025-12-30",,,
14,2026-01-05 DIV,,ZEQT - BMO All-Equity ETF: Cash dividend distr...,$0.00,$0.23,$0.78
15,,,"2026-01-05, record date of 2025-12-30",,,
16,2026-01-05 DIV,,XEQT - iShares Core Equity ETF Portfolio: Cash...,$0.00,$2.37,$3.15
17,,,"on 2026-01-05, record date of 2025-12-30",,,
18,2026-01-06,BUY,CDZ - iShares S&P/TSX Canadian Dividend ETF: B...,$0.12,$0.00,$3.03
19,,,$41.31 per share (executed at 2026-01-05),,,
20,2026-01-06,BUY,ZEB - BMO Equal Weight Banks Index ETF: Bought...,$0.30,$0.00,$2.73
21,,,per share (executed at 2026-01-05),,,
22,2026-01-06 RECALL,,ZGLD - BMO Gold Bullion ETF - CAD: Loan of 4.0...,$0.00,$0.00,$2.73
23,,,(executed at 2026-01-06),,,
24,2026-01-07,BUY,ZEQT - BMO All-Equity ETF: Bought 0.0110 share...,$0.23,$0.00,$2.50
25,,,(executed at 2026-01-06),,,
26,2026-01-07,BUY,XEQT - iShares Core Equity ETF Portfolio: Boug...,$2.37,$0.00,$0.13
27,,,per share (executed at 2026-01-06),,,
28,2026-01-07 DIV,,VDY - Vanguard Investments Canada Inc. - FTSE ...,$0.00,$0.35,$0.48
29,,,"Yield Index ETF: Cash dividend distribution, r...",,,
30,,,date of 2025-12-30,,,
31,2026-01-07 DIV,,VFV - Vanguard S&P 500 Index ETF: Cash dividen...,$0.00,$1.25,$1.73
32,,,"2026-01-07, record date of 2025-12-30",,,
33,2026-01-09,BUY,VDY - Vanguard Investments Canada Inc. - FTSE ...,$0.35,$0.00,$1.38
34,,,Yield Index ETF: Bought 0.0056 shares at $62.1...,,,
35,,,2026-01-08),,,
36,2026-01-09,BUY,VFV - Vanguard S&P 500 Index ETF: Bought 0.007...,$1.24,$0.00,$0.14
37,,,share (executed at 2026-01-08),,,
38,2026-01-15 DIV,,PZA - Pizza Pizza Royalty Corp: Cash dividend ...,$0.00,$0.33,$0.47
39,,,"2026-01-15, record date of 2025-12-31",,,
40,2026-01-15,FPLINT,Stock lending monthly interest payment,$0.00,$0.01,$0.48
41,2026-01-16,BUY,PZA - Pizza Pizza Royalty Corp: Bought 0.0204 ...,$0.33,$0.00,$0.15
42,,,(executed at 2026-01-15),,,
43,2026-01-16,LOAN,"T - AT&T, Inc.: 3.0000 Shares on loan (execute...",$0.00,$0.00,$0.15
44,2026-01-20 RECALL,,"T - AT&T, Inc.: Loan of 3.0000 shares terminat...",$0.00,$0.00,$0.15
45,2026-01-21,LOAN,ZGLD - BMO Gold Bullion ETF - CAD: 4.0000 Shar...,$0.00,$0.00,$0.15
46,,,2026-01-21),,,
47,2026-01-22 RECALL,,ZGLD - BMO Gold Bullion ETF - CAD: Loan of 4.0...,$0.00,$0.00,$0.15
48,,,(executed at 2026-01-22),,,
49,2026-01-23 DIV,,VDY - Vanguard Investments Canada Inc. - FTSE ...,$0.00,$0.35,$0.50

In [75]:
data

,0,1,2,3,4,5
0,,Activity - Current period,,,,
1,Date,Transaction Description,,,Debit ($) Credit ($) Balance ($),
2,2026-01-02,BUY,BN - Brookfield Corp.: Bought 0.0039 shares at...,$0.25,$0.00,$0.13
3,,,2025-12-31),,,
4,2026-01-02 DIV,,WN - George Weston Ltd.: Cash dividend distrib...,$0.00,$0.49,$0.62
...,...,...,...,...,...,...
58,,,at 2026-01-29),,,
59,2026-01-30 DIV,,CDZ - iShares S&P/TSX Canadian Dividend ETF: C...,$0.00,$0.12,$0.27
60,,,"received on 2026-01-30, record date of 2026-01-27",,,
61,2026-01-30,LOAN,SCHD - Schwab US Dividend Equity ETF: 3.0000 S...,$0.00,$0.00,$0.27
62,,,2026-01-30),,,

In [76]:
data = data.drop([0,1])
data.rename(columns={0 : "date", 1: "transaction", 2: "info", 3: "debit", 4: "credit", 5:"balance"},inplace=True)
data = data.reset_index(drop=True)

In [77]:
data.head(100)

,date,transaction,info,debit,credit,balance
0,2026-01-02,BUY,BN - Brookfield Corp.: Bought 0.0039 shares at...,$0.25,$0.00,$0.13
1,,,2025-12-31),,,
2,2026-01-02 DIV,,WN - George Weston Ltd.: Cash dividend distrib...,$0.00,$0.49,$0.62
3,,,record date of 2025-12-15,,,
4,2026-01-02,LOAN,ZGLD - BMO Gold Bullion ETF - CAD: 4.0000 Shar...,$0.00,$0.00,$0.62
...,...,...,...,...,...,...
56,,,at 2026-01-29),,,
57,2026-01-30 DIV,,CDZ - iShares S&P/TSX Canadian Dividend ETF: C...,$0.00,$0.12,$0.27
58,,,"received on 2026-01-30, record date of 2026-01-27",,,
59,2026-01-30,LOAN,SCHD - Schwab US Dividend Equity ETF: 3.0000 S...,$0.00,$0.00,$0.27
60,,,2026-01-30),,,

In [78]:
cond = data['date']== ""
data[cond]

,date,transaction,info,debit,credit,balance
1,,,2025-12-31),,,
3,,,record date of 2025-12-15,,,
5,,,2026-01-02),,,
7,,,(executed at 2026-01-02),,,
9,,,"received on 2026-01-05, record date of 2025-12-30",,,
11,,,"received on 2026-01-05, record date of 2025-12-30",,,
13,,,"2026-01-05, record date of 2025-12-30",,,
15,,,"on 2026-01-05, record date of 2025-12-30",,,
17,,,$41.31 per share (executed at 2026-01-05),,,
19,,,per share (executed at 2026-01-05),,,
21,,,(executed at 2026-01-06),,,
23,,,(executed at 2026-01-06),,,
25,,,per share (executed at 2026-01-06),,,
27,,,"Yield Index ETF: Cash dividend distribution, r...",,,
28,,,date of 2025-12-30,,,
30,,,"2026-01-07, record date of 2025-12-30",,,
32,,,Yield Index ETF: Bought 0.0056 shares at $62.1...,,,
33,,,2026-01-08),,,
35,,,share (executed at 2026-01-08),,,
37,,,"2026-01-15, record date of 2025-12-31",,,
40,,,(executed at 2026-01-15),,,
44,,,2026-01-21),,,
46,,,(executed at 2026-01-22),,,
48,,,"Yield Index ETF: Cash dividend distribution, r...",,,
49,,,date of 2026-01-16,,,
51,,,Yield Index ETF: Bought 0.0055 shares at $63.2...,,,
52,,,2026-01-23),,,
54,,,2026-01-28),,,
56,,,at 2026-01-29),,,
58,,,"received on 2026-01-30, record date of 2026-01-27",,,
60,,,2026-01-30),,,

In [79]:
data['date'] = data['date'].replace('',None)
data['crit'] = data['date'].notna().cumsum()

In [80]:
data.groupby("crit", as_index=False).agg({
"date": "first",
"transaction": "first",
"info": lambda x: " ".join(x.dropna().astype(str).str.strip()),
"debit": "first",
"credit": "first",
"balance": "first"
}).drop(columns="crit")

,date,transaction,info,debit,credit,balance
0,2026-01-02,BUY,BN - Brookfield Corp.: Bought 0.0039 shares at...,$0.25,$0.00,$0.13
1,2026-01-02 DIV,,WN - George Weston Ltd.: Cash dividend distrib...,$0.00,$0.49,$0.62
2,2026-01-02,LOAN,ZGLD - BMO Gold Bullion ETF - CAD: 4.0000 Shar...,$0.00,$0.00,$0.62
3,2026-01-05,BUY,WN - George Weston Ltd.: Bought 0.0051 shares ...,$0.49,$0.00,$0.13
4,2026-01-05 DIV,,CDZ - iShares S&P/TSX Canadian Dividend ETF: C...,$0.00,$0.12,$0.25
5,2026-01-05 DIV,,ZEB - BMO Equal Weight Banks Index ETF: Cash d...,$0.00,$0.30,$0.55
6,2026-01-05 DIV,,ZEQT - BMO All-Equity ETF: Cash dividend distr...,$0.00,$0.23,$0.78
7,2026-01-05 DIV,,XEQT - iShares Core Equity ETF Portfolio: Cash...,$0.00,$2.37,$3.15
8,2026-01-06,BUY,CDZ - iShares S&P/TSX Canadian Dividend ETF: B...,$0.12,$0.00,$3.03
9,2026-01-06,BUY,ZEB - BMO Equal Weight Banks Index ETF: Bought...,$0.30,$0.00,$2.73
10,2026-01-06 RECALL,,ZGLD - BMO Gold Bullion ETF - CAD: Loan of 4.0...,$0.00,$0.00,$2.73
11,2026-01-07,BUY,ZEQT - BMO All-Equity ETF: Bought 0.0110 share...,$0.23,$0.00,$2.50
12,2026-01-07,BUY,XEQT - iShares Core Equity ETF Portfolio: Boug...,$2.37,$0.00,$0.13
13,2026-01-07 DIV,,VDY - Vanguard Investments Canada Inc. - FTSE ...,$0.00,$0.35,$0.48
14,2026-01-07 DIV,,VFV - Vanguard S&P 500 Index ETF: Cash dividen...,$0.00,$1.25,$1.73
15,2026-01-09,BUY,VDY - Vanguard Investments Canada Inc. - FTSE ...,$0.35,$0.00,$1.38
16,2026-01-09,BUY,VFV - Vanguard S&P 500 Index ETF: Bought 0.007...,$1.24,$0.00,$0.14
17,2026-01-15 DIV,,PZA - Pizza Pizza Royalty Corp: Cash dividend ...,$0.00,$0.33,$0.47
18,2026-01-15,FPLINT,Stock lending monthly interest payment,$0.00,$0.01,$0.48
19,2026-01-16,BUY,PZA - Pizza Pizza Royalty Corp: Bought 0.0204 ...,$0.33,$0.00,$0.15
20,2026-01-16,LOAN,"T - AT&T, Inc.: 3.0000 Shares on loan (execute...",$0.00,$0.00,$0.15
21,2026-01-20 RECALL,,"T - AT&T, Inc.: Loan of 3.0000 shares terminat...",$0.00,$0.00,$0.15
22,2026-01-21,LOAN,ZGLD - BMO Gold Bullion ETF - CAD: 4.0000 Shar...,$0.00,$0.00,$0.15
23,2026-01-22 RECALL,,ZGLD - BMO Gold Bullion ETF - CAD: Loan of 4.0...,$0.00,$0.00,$0.15
24,2026-01-23 DIV,,VDY - Vanguard Investments Canada Inc. - FTSE ...,$0.00,$0.35,$0.50
25,2026-01-26,BUY,VDY - Vanguard Investments Canada Inc. - FTSE ...,$0.35,$0.00,$0.15
26,2026-01-28,LOAN,PZA - Pizza Pizza Royalty Corp: 2.0000 Shares ...,$0.00,$0.00,$0.15
27,2026-01-29 RECALL,,PZA - Pizza Pizza Royalty Corp: Loan of 2.0000...,$0.00,$0.00,$0.15
28,2026-01-30 DIV,,CDZ - iShares S&P/TSX Canadian Dividend ETF: C...,$0.00,$0.12,$0.27
29,2026-01-30,LOAN,SCHD - Schwab US Dividend Equity ETF: 3.0000 S...,$0.00,$0.00,$0.27